"""Initial schema: users, conversations, gmail/gcal/gdrive caches, sync_status, audit_log.

Hand-written (not autogenerated) to exactly mirror app/db/models.py. Creates the
pgvector extension first since every *_cache table has a `vector(1536)` column.

Revision ID: 0001
Revises:
Create Date: 2026-09-17
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 1536  # must match Settings.embedding_dimensions / OpenAI text-embedding-3-small


def upgrade() -> None:
    # pgvector must be enabled before any table can declare a `vector(N)` column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # --- users: one row per person who has connected Google via OAuth ---
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("google_access_token", sa.Text(), nullable=True),   # Fernet-encrypted
        sa.Column("google_refresh_token", sa.Text(), nullable=True),  # Fernet-encrypted
        sa.Column("google_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.create_index("ix_users_email", "users", ["email"])

    # --- conversations: query/intent/response log, also backs "last 5 queries" context ---
    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("intent", postgresql.JSONB(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("actions_taken", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_index("ix_conversations_created_at", "conversations", ["created_at"])

    # --- gmail_cache: synced Gmail messages + embeddings ---
    op.create_table(
        "gmail_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("email_id", sa.String(255), nullable=False),
        sa.Column("thread_id", sa.String(255), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("sender", sa.String(255), nullable=True),
        sa.Column("recipients", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("body_preview", sa.Text(), nullable=True),
        sa.Column("labels", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_gmail_user_email", "gmail_cache", ["user_id", "email_id"])
    op.create_index("ix_gmail_cache_user_id", "gmail_cache", ["user_id"])
    op.create_index("ix_gmail_cache_sender", "gmail_cache", ["sender"])
    op.create_index("ix_gmail_cache_received_at", "gmail_cache", ["received_at"])
    # ANN index for cosine similarity search. lists=100 is a reasonable default for
    # tens-of-thousands of rows per shard; retune (roughly sqrt(row_count)) as data grows.
    op.create_index(
        "ix_gmail_embedding", "gmail_cache", ["embedding"],
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    # --- gcal_cache: synced Calendar events + embeddings ---
    op.create_table(
        "gcal_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("event_id", sa.String(255), nullable=False),
        sa.Column("calendar_id", sa.String(255), nullable=False, server_default="primary"),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("attendees", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("status", sa.String(32), nullable=False, server_default="confirmed"),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_gcal_user_event", "gcal_cache", ["user_id", "event_id"])
    op.create_index("ix_gcal_cache_user_id", "gcal_cache", ["user_id"])
    op.create_index("ix_gcal_cache_start_time", "gcal_cache", ["start_time"])
    op.create_index(
        "ix_gcal_embedding", "gcal_cache", ["embedding"],
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    # --- gdrive_cache: synced Drive file metadata + content preview + embeddings ---
    op.create_table(
        "gdrive_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("file_id", sa.String(255), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(128), nullable=True),
        sa.Column("content_preview", sa.Text(), nullable=True),
        sa.Column("web_view_link", sa.Text(), nullable=True),
        sa.Column("parents", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_gdrive_user_file", "gdrive_cache", ["user_id", "file_id"])
    op.create_index("ix_gdrive_cache_user_id", "gdrive_cache", ["user_id"])
    op.create_index("ix_gdrive_cache_modified_at", "gdrive_cache", ["modified_at"])
    op.create_index(
        "ix_gdrive_embedding", "gdrive_cache", ["embedding"],
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    # --- sync_status: last successful sync per (user, service), backs /sync/status ---
    op.create_table(
        "sync_status",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("service", sa.String(32), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("error", sa.Text(), nullable=True),
    )
    op.create_unique_constraint("uq_sync_user_service", "sync_status", ["user_id", "service"])
    op.create_index("ix_sync_status_user_id", "sync_status", ["user_id"])

    # --- audit_log: immutable record of every write/side-effecting action taken ---
    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("service", sa.String(32), nullable=False),
        sa.Column("resource_id", sa.String(255), nullable=True),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("details", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_audit_log_user_id", "audit_log", ["user_id"])
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])


def downgrade() -> None:
    # Drop in reverse dependency order (children before the `users` table they reference).
    op.drop_table("audit_log")
    op.drop_table("sync_status")
    op.drop_table("gdrive_cache")
    op.drop_table("gcal_cache")
    op.drop_table("gmail_cache")
    op.drop_table("conversations")
    op.drop_table("users")
    op.execute("DROP EXTENSION IF EXISTS vector")
